name: project_environment
dependencies:
  - python=3.8.18
  - scikit-learn
  - numpy
  - pip
  - pip:
    # Base AzureML SDK
    - azureml-core

    # Must match AzureML SDK version.
    - azureml-defaults

    # Training deps
    - scikit-learn

    # Scoring deps
    - inference-schema[numpy-support]

    # MLOps with R
    - azure-storage-blob

    # LightGBM boosting lib
    - lightgbm
    - LightGBM

    # Job lib
    - joblib

    # Pandas
    - pandas==1.1.3

    # Additional AzureML packages (from the previous version)
    - azureml-mlflow
    - azureml-telemetry